site_name = "example.com"
mode = "fm"
uv = true
verbose = true
releases_retain_limit = 1
python_version = "3.12"
remove_remote = true
backups = true

[common_site_config]
socketio_port = 9000

[[apps]]
repo = "frappe/frappe"
ref = "develop"

[[apps]]
repo = "frappe/erpnext"
ref = "develop"

[build_frappe]
name = "ghcr.io/rtcamp/frappe-deployer-frappe"
tag = "v0.1"
base_name = "python"
base_tag = "3.12.12-slim"
platforms = [ "linux/amd64" ]
distro = "slim"
labels = [ "author=rtCamp", "org.opencontainers.image.source=https://github.com/rtcamp/frappe-deployer" ]

[build_nginx]
name = "ghcr.io/rtcamp/frappe-deployer-nginx"
tag = "v0.1"
base_name = "nginx"
base_tag = "latest"
platforms = [ "linux/amd64" ]
labels = [ "author=rtCamp", "org.opencontainers.image.source=https://github.com/rtcamp/frappe-deployer" ]
