site_name = 'site.localhost'
mode = 'host'  # Can be 'host' or 'fm'

[[apps]]
repo = 'frappe/frappe'
ref = 'main'

[[apps]]
repo = 'frappe/erpnext'
ref = 'main'

[host]
bench_path = '/home/frappe/frappe/sites/cicd.localhost/workspace'
