[tool.poetry]
name = "frappe-deployer"
version = "0.7.9"
description = "Automates setup and management of Frappe/Frappe-Manager environments using flags or config file."
authors = ["Alok Singh <alokmilenium@gmail.com>"]
license = "MIT"
#readme = "readme.org"

[tool.poetry.scripts]
frappe-deployer = "frappe_deployer.main:cli_entrypoint"

[tool.poetry.dependencies]
python = "^3.10"
frappe-manager = { git = "https://github.com/rtcamp/frappe-manager.git", branch = "develop" }
gitpython = "^3.1.43"
typer = {version = "^0.9.0", extras = ["all"]}
toml = "^0.10.2"

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
