[tool.poetry]
name = "frappe-deployer"
version = "0.0.0"
description = ""
authors = ["Alok Singh <alokmilenium@gmail.com>"]
license = "MIT"
readme = "readme.org"

[tool.poetry.scripts]
fx = "frappe_deployer.main:cli_entrypoint"

[tool.poetry.dependencies]
python = "3.11.9"
frappe-manager = "^0.16.0"
gitpython = "^3.1.43"
typer = {version = "^0.9.0", extras = ["all"]}
toml = "^0.10.2"
asyncio = "^3.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
